# MySQL Data Source Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api
#server:
#  port: 8443
#  ssl:
#    key-store: file:C:\Users\MyPC/mykeys.jks
#    key-store-password: letmein
#    key-password: letmein
logging:      
#  file.name: logs/TacoCloud.log
#  file.path: 
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
    tacos: DEBUG
greeting:
  welcome: You are using ${spring.application.name}.
taco:
  orders:
    pageSize: 10  
#    hikari:
#      schema: schema.sql
#    data:
#  sql:
#    init:
#      mode: always
#      schema-locations:
#      - schema-me.sql
#      data-locations:
#      - ingredient_data.sql
# SQL Initialization Script Configuration

    